services:
  mysqldb:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    environment:
      - PMA_HOST=mysqldb
      - PMA_PORT=3306
    env_file:
      - .env
    ports:
      - '8080:80'
    depends_on:
      - mysqldb
