version: '3.8'

networks:
  mylinks_app:
    external: true

services:
  mylinks:
    restart: always
    container_name: MyLinks
    build:
      context: .
    ports:
      - '127.0.0.1:5000:3000'
    env_file:
      - .env
    networks:
      - mylinks_app
